README.md, REQUIRE, images/GenerateImages.jl, images/draw_swatches.jl, src/Colors.jl, src/algorithms.jl, src/colormaps.jl, src/conversions.jl, src/differences.jl, src/display.jl, src/parse.jl, src/utilities.jl, test/conversion.jl
Probably the only thing to discuss is whether the literal string macro should be called `Colorant"red"` or `colorant"red"`. Since it also works for strings like `"rgba(1,0,0,0.5)"`, I'm just going to preemptively say that anyone who wishes it could be called `"Color"` or `"color"` is going to have to be extremely persuasive.
=> Second renaming, add Colorant string macro, drop Graphics dependency

src/algorithms.jl, src/colormaps.jl, test/conversion.jl
As @jiahao has pointed out, arithmetic is complicated with Colors; in particular, nonlinear colorspaces should not be treated in a cavalier fashion. In Color.jl, we've had support for arithmetic through a more careful procedure: `a+b -> original_colorspace(XYZ(a) + XYZ(b))`, exploiting the fact that `XYZ` is, in fact, a vector space.
The problem with this seemingly-rational approach is that it fails due to gamut-correction. This was discovered while adding a "sanity-check" for the diagonal in the diagram that appears in https://github.com/JuliaGraphics/ColorVectorSpace.jl (@jiahao, I think you'll like that diagram). For example, one identity that should be satisfied in *any* colorspace is `mean(a,a) == a`, where `mean(a,b)` averages `a` and `b`. Let's see how we fare with Color.jl:
```jl …
```
=> Support arithmetic only for linear color spaces

REQUIRE, src/Colors.jl, src/algorithms.jl, src/colormaps.jl, src/colormatch.jl, src/conversions.jl, src/differences.jl, src/maps_data.jl, src/names_data.jl, src/parse.jl, src/utilities.jl, test/conversion.jl
Incorporate and fix deprecations caused by the wonderful JeffBezanson/FixedPointNumbers.jl#27. This also commits to julia 0.4 and deletes cruft.
This won't pass tests until JeffBezanson/FixedPointNumbers.jl#31 gets tagged. I'll re-run the travis jobs when that happens, but submitting for comments.
=> UFixed transition and commit to julia 0.4

src/colormaps.jl
I can't remember where this originally came up, but I believe that @m-lohmann or @tbreloff discovered that distinguishability improves if you ensure that all candidate colors are within the gamut of RGB.
=> distinguishable_colors: restrict candidates to RGB-realizable colors

src/utilities.jl
I believe this syntax is simpler and is supported on 0.4 too.
=> Fix 0.5 depwarn about getfield syntax

src/conversions.jl, test/conversion.jl
CC @gabrielgellner. All I did was make sure I convert to the output eltype (e.g., `Float32`) before performing any arithmetic operations.
=> Fix RGB->HSL conversion InexactError. Fixes ColorTypes #40

.travis.yml, REQUIRE, src/algorithms.jl, test/conversion.jl
Requires JuliaLang/Compat.jl#280 and a new `Compat` tag.
=> Fix depwarn on 0.6 due to vectorized functions

src/conversions.jl, test/conversion.jl
In the expression for conversion from RGB->HSI, the argument to the square root is written as
```jl
r^2+g^2+b^2-r*g-r*b-g*b
```
but an analytically-identical expression is
```jl
((r-g)^2 + (r-b)^2 + (g-b)^2)/2
```
This latter version has the distinct advantage that it's guaranteed to be nonnegative even in the face of roundoff error. Fixes #257.
=> Use nonnegative definite expression in arg for sqrt

REQUIRE, src/conversions.jl, test/conversion.jl
Fixes deprecation warnings from ColorTypes
=> Switch to explicit reinterpret for UInt32 <---> RGB24 & friends

src/display.jl
Dear all,
the malformed XML tag may trigger a warning when converting the generated SVG with e.g inkscape. Conversion is successful though. Very minor issue in a rather obscure use case :)
Best,
Stephan
=> Fixed missing "=" in xml tag in Base.show

src/Colors.jl, src/promotions.jl, test/conversion.jl
Amazing that we haven't noticed the lack of these previously. These rules aren't perfect, but I'll file an issue detailing what needs to improve.
@tkelman, I also noticed some stale (>1 year old) `@deprecate` statements, which I deleted. Does deleting those mean we need to do a minor version bump?
=> Add promotions between Gray and multi-component Colorants

src/colormaps.jl
This does not fix the use of `@test_approx_eq_eps` in the test. (Since it's less important and might require defining a correct `isapprox` method....)
=> Fix 0.6 depwarns in src/

REQUIRE, src/colormatch.jl, src/differences.jl
~~**DO NOT MERGE NOW!!!!**~~
~~This requires https://github.com/JuliaLang/Compat.jl/pull/325 and a new tag. I'm using this (and other) PR's to check if the implementation is correct.~~
Ready now.
=> Fix 0.6 abstract type declaration depwarn

src/parse.jl, test/conversion.jl
fix parsing of "#rgb" to conform to the CSS specification
=> Fix parsing of 3-digit RGB (#rgb) (#280)

src/display.jl
Fixes #283 
This rewrites the logic to choose the rectangle size for each color when rendering to SVG. The result should be that: 
* a much wider range of aspect ratios are faithfully preserved (the specific range is 0.16 to 7.2, which is a consequence of the particular max width, max height, and max pixel size chosen)
* aspect ratios outside that range are clamped to the nearest aspect ratio in the range
* color matrices with `m` > `n` are always drawn taller than they are wide, and vice versa
* a color matrix with `m + 1` rows is never shorter than a color matrix with `m` rows, and a color matrix with `n + 1` columns is never thinner than a color matrix with `n` columns
Here's the particular motivating example from #283 after this change:
I also made another minor change: previously, …
=> more faithful preservation of aspect ratio when displaying as SVG

src/conversions.jl, test/conversion.jl, test/runtests.jl
Fixes https://github.com/JuliaGraphics/ColorTypes.jl/issues/91. The tests I added for that issue also detect a problem in `convert(HSI, c)` in that it failed to account for the possibility of numeric overflow when using FixedPoint types.
=> Fix conversions to Gray

REQUIRE, src/Colors.jl, src/conversions.jl
* remove `__precompile__()` since it's now the default
* Add parentheses to avoid bitshift deprecation warning (which just got turned on by https://github.com/JuliaLang/julia/pull/28389 )
=> fix more deprecations on 0.7-rc2

src/Colors.jl, src/promotions.jl
This PR eliminates duplicate types defined in ColorTypes.jl. I am submitting another PR for the Images.jl project as well.
Depends on: https://github.com/JuliaGraphics/ColorTypes.jl/pull/111
=> Eliminate duplicate types already defined in ColorTypes.jl

Manifest.toml, REQUIRE
CC @juliohm. This one will be more painful because we also have to correct METADATA for the 0.9.3 release.
=> Fix version dependency on ColorTypes

src/utilities.jl, test/utilities.jl
From Julia 1.1 on, `range(start, stop; kwargs...)` is supported complementary to `range(start; stop, kwargs...)`. This PR adds the former method for `Colorant`s.
=> Support range(start, stop; kwargs...)

docs/src/colorspaces.md, src/differences.jl, test/colordiff.jl, test/din99.jl
* make metric a keyword argument to `colordiff`; this enables broadcast, i.e., `colordiff.(imgA, imgB; metric=DE_2000())`
* support `Number` input; `Number` is interpreted as `Gray`.
=> enhance Colordiff API

src/display.jl, test/display.jl
This reduces the size of SVG document and the rendering time.
So this is one way to mitigate the issue #317.
=> Use stroke instead of fill (rect) with swatch reduction for large matrix

src/conversions.jl, test/conversion.jl
This improves `srgb_compand` and `invert_srgb_compand`(renamed rgb->srgb) with almost no loss in accuracy. (#351)
=> Speed up RGB <--> XYZ conversions

src/colormaps.jl, test/colormaps.jl
I just did the minimum viable fix. I think that the way in which keyword arguments are handled here is very error-prone. Maybe the constants in `maps_data.jl` should be `NamedTuples` of `NamedTuples` to avoid manual indexing at various places.
=> Fix colormap keyword argument handling

src/display.jl, test/display.jl
This adds support for displaying a single `TransparentColor` and vector of `TransparentColor` as SVG.
=> Add support for displaying `TransparentColor` as SVG (#343)

src/parse.jl, test/parse.jl
This fixes #357.
- Modify white space handling
- Add error message about 8-digit or 4-digit hex notation
- Add support for some CSS4 notations
- Add tests
- Speed up parsing averagely
=> Modify strictness of color parser (#357)

src/Colors.jl, src/precompile.jl, src/utilities.jl
This adds some precompile statements to reduce latency. Because the methods are simple to infer, the savings are modest, but combined with precompiles in other packages (FixedPointNumbers, ColorTypes, ColorVectorSpace) I'm getting latency reductions of ~30% for some common operations. So these seem worth having.
=> Add some precompiles

Project.toml, docs/src/colorspaces.md, docs/src/index.md, src/Colors.jl, test/conversion.jl
One thing I failed to anticipate is that because this reexports names in ColorTypes, I needed to create new deprecated bindings if I didn't want to cause a depwarn every time the package is loaded. It doesn't appear to cause a conflict, though:
```julia
julia> using ColorTypes
julia> RGB1
WARNING: ColorTypes.RGB1 is deprecated, use XRGB instead.
likely near REPL[2]:1
XRGB
julia> using Colors
julia> RGB1
WARNING: ColorTypes.RGB1 is deprecated, use XRGB instead.
likely near REPL[4]:1
XRGB
```
and in a fresh session
```julia
julia> using ColorTypes, Colors
julia> RGB1
WARNING: Colors.RGB1 is deprecated, use XRGB instead.
likely near REPL[2]:1
XRGB
```
Normally I'd say this is unambiguously a patch release (and that's what I've done here), but since there are the "new" bindings I'd be open to …
=> Support ColorTypes 0.9

src/parse.jl, test/parse.jl
This is another solution for the issue #386. (cf. PR #388)
This parser is somewhat loose. For example, "deep skyblue" or "dark golden rod" are acceptable even though they are not the X11 named colors.
=> Re-support parsing the X11 color names with spaces with a depwarn

src/conversions.jl, test/conversion.jl
As suspected by @kimikage, that defensive `min` takes quite a lot of time. This results in a ~2x speed improvement for elementwise gray conversion.
=> Speed up grayscale conversion

Project.toml, docs/make.jl, src/Colors.jl, src/utilities.jl, test/utilities.jl
cf. issue #353
Since `Base.hex` is no longer public, this `hex` does not extend it (i.e. this is `Colors.hex`).
Because of the backward compatibility, `hex(c::ColorAlpha)` returns "AARRGGBB" with a depwarn for now.
The new methods are not fully optimized, so the performance improvement is a future task.
=> Add support for specifying the style of `hex`

src/parse.jl, test/parse.jl
This adds the support for parsing 8-digit and 4-digit hex notations following the manner mentioned in https://github.com/JuliaGraphics/Colors.jl/issues/353#issue-495280410.
Do not merge this PR before the decision of #353 for the consistency.
=> [RFC] Add support for parsing 8-digit and 4-digit hex notations

Project.toml, src/Colors.jl
Although I have doubts about the need, I think it is good to backport #395 for the consistency.
=> Backport #395 and Release v0.10.2

src/conversions.jl, src/differences.jl
On Colors.jl v0.11, ColorTypes.jl v0.8 (v0.8.0) is no longer supported (cf #383). So, we can use `chroma()` and `hue()`, which were added on ColorTypes.jl v0.8.1 (https://github.com/JuliaGraphics/ColorTypes.jl/pull/135).
=> Use chroma() and hue()

docs/src/colormapsandcolorscales.md, docs/src/constructionandconversion.md, src/Colors.jl, src/algorithms.jl, src/colormaps.jl, src/conversions.jl, src/utilities.jl, test/utilities.jl
This adds a new function `normalize_hue`, which simply wraps the hue angles to [0,360].
This PR does not solve the issue #379, but adding the hue normalization to `weighted_color_mean` helps handle hues in `range`.
=> Add normalize_hue and Enhance hue handling in `range`

docs/Project.toml, docs/crosssectionalcharts.jl, docs/make.jl, docs/src/advancedfunctions.md, docs/src/colordifferences.md, docs/src/constructionandconversion.md, docs/src/index.md, docs/src/namedcolors.md
This adds the cross-sectional charts previewed in https://github.com/JuliaGraphics/Colors.jl/issues/398#issuecomment-588270497.
Although there is discussion about the axis assignment (cf. https://github.com/JuliaGraphics/Colors.jl/issues/398#issuecomment-589399452), but in this PR, it is as I originally defined. Since I am currently modifying the conversion codes for `HSV`, `HSL`, and `HSI`, I just want a way to visually check the S-V, S-L and S-I planes. (**Edit:** see: #407)
In addition, this PR changes some documents.
=> Add cross-sectional charts and some examples to docs

src/conversions.jl, src/utilities.jl, test/conversion.jl
~I'm working on benchmarking and tuning. So, this is a draft PR now.~ ~I want to merge #406 first to check HSx-->RGB conversions.~ (**Edit**: Done)
This fixes #378 and fixes #379.
This adds the clamping and hue normalization for sources to HSx-->RGB conversions. This also adds the clamping for destinations to HSI-->RGB conversion.
Despite the additional mechanism, at the expense of some accuracy, this speeds ​​up the conversions with some parameter combinations.
Note the following change (cf. https://github.com/JuliaGraphics/Colors.jl/issues/379#issuecomment-590213678):
```julia
julia> RGB(1,0,0)|>HSV
HSV{Float32}(0.0f0,1.0f0,1.0f0)
```
=> Improve HSV/HSL/HSI conversions (Fixes #378, #379)

src/conversions.jl, src/utilities.jl, test/utilities.jl
See: https://github.com/JuliaGraphics/Colors.jl/issues/378#issuecomment-588179535
I had forgotten the alpha outside of [0,1].  Although some slowing down is inevitable, it is still faster than pre-PR #387.
=> Re-enable clamping in `hex`

docs/colordiffcharts.jl, docs/make.jl, docs/src/colordifferences.md, src/differences.jl
This update the docs for color differences (cf. https://github.com/JuliaGraphics/Colors.jl/issues/398#issuecomment-591360224).
I changed the example for `colordiff`, i.e. removed the strange `parse`.
I also add a doctest for the difference between an `HSV` color and an `HSL` color. It may help check the PR #407. ~The PR #407 is ready for merging, but there may be room for improvement on the `fma`/`muladd` (cf. https://github.com/JuliaGraphics/Colors.jl/pull/407#discussion_r386098781). So, it is another reasonable option to merge this PR first.~ ~(**Edit:** Either is fine now.)~
PR #407 was merged.
=> Add charts for `colordiff` to docs and Use docstrings for metrics

src/differences.jl, test/conversion.jl
This simplifies the Euclidean difference metrics.
I am planning to clean up "differences.jl", but it is likely that there will be many fixes but no breaking changes. Therefore, I extracted only the part related to the type hierarchy. This PR is the successor to PR #409. (**Edit:** PR #409 was merged.)
=> Add abstract type EuclideanDifferenceMetric

src/conversions.jl, src/utilities.jl, test/conversion.jl, test/utilities.jl
This was invented five months ago (cf. https://github.com/JuliaGraphics/Colors.jl/issues/351#issuecomment-538997861), and Julia v1.3 was released in the meantime.
SIMD optimization is difficult in RGB <--> XYZ conversions. so this change has no dramatic improvement but is still effective.
closes #351.
**Edit:**
However, if we add the partial support for color gamuts in the near future (e.g. in v0.13), it is a good idea to leave this PR open, because the codes for gamma compression/expansion will be moved to a new file "gamuts.jl" (cf. #412)
=> Speed up RGB <--> XYZ conversions again

.travis.yml, Project.toml, appveyor.yml, src/Colors.jl, src/conversions.jl, src/promotions.jl, test/conversion.jl
~We are currently undergoing a major renovation of ColorTypes.jl. So, this PR is a preview.~
Since gray-->rgb conversions were supported and some rgb-->rgb conversions were fixed in ColorTypes.jl v0.10, this PR delegates the conversions to ColorType.jl.
=> Move promotion rules and some typealiases to ColorTypes.jl v0.10

docs/src/namedcolors.md, src/parse.jl
The colors from the Julia logo are frequently used for various visualizations and logo designs, private or public, so I thought they would be useful in this package.
At the same time, I did not put them in the named colors namespace since they are unique to Julia, not a shared color name space like X11 or SVG (cf [this comment](https://github.com/JuliaGraphics/Colors.jl/issues/361#issuecomment-563033679) by @kimikage). For the same reason, they are not exported, just mentioned in the docs.
Happy to make any changes.
(RGB color codes just extracted from the svg in the JuliaLang/julia repository with Inkscape).
=> Add a constant for the colors in the Julia logo

.github/workflows/CompatHelper.yml, README.md
This removes the "setup-julia" action because we have Julia installed by default.
This schedules the CompatHelper to run once a day. Perhaps we are more familiar with the FixedPointNumbers and ColorTypes than the CompatHelper.:smile:
This also adds the new PkgEval badge. Previously there was a separate "Package Evaluator" column, but I put it in the "Build Status" column.
=> Simplify CompatHelper settings and Add PkgEval badge

docs/colordiffcharts.jl, docs/src/index.md
This also fixes the invalid `<kbd>` HTML tag.
=> Use logo color constant in docs (ColorDiffCharts)

Project.toml
I would like to release a patch to make PR #418 available for the end users. The constant introduced in PR #418 have not been exported, so there is no change of the public API. I think there are no compatibility issues since the constant will be used by the end users or "tests" in the downstream packages.
I also want to include PR #421 (or part of it) in v0.12.1. However, the compatibility impact of PR #421 is not clear.
cc: @timholy, @johnnychen94 
**Edit:**
The PR #424 does not change the public API, so it may be included in v0.12.1.
**Edit2:**
Half a month has passed, so I will merge PR #426 and release v0.12.1. (Although PR #426 does not change the source code, it is related with PR #418.)
=> Version 0.12.1

src/utilities.jl, test/utilities.jl
This fixes #416, but leaves the weight type conversion (https://github.com/JuliaGraphics/Colors.jl/issues/416#issuecomment-619586809).
`Gray{Bool}`s do not throw a `DomainError` due to their type now, although the `InexactError` is likely to occur. Because of the weight type conversion, the following throws an `InexactError`.
```julia
julia> weighted_color_mean(0.5, Gray{Bool}(1), Gray{Bool}(1))
ERROR: InexactError: Bool(0.5)
```
The range checking of `w1` is done in the type of `w1` in order to more intuitive error messages.
```julia
julia> weighted_color_mean(-0.001, Gray24(0), Gray24(1))
ERROR: ArgumentError: FixedPointNumbers.Normed{UInt8,8} is an 8-bit type representing 256 values from 0.0 to 1.0; cannot represent -0.001
julia> weighted_color_mean(1.00000005, Gray(0.0f0), …
```
=> Fix error types and conditions in `weighted_color_mean`

src/conversions.jl
These are the remains of https://github.com/JuliaGraphics/Colors.jl/issues/354#issuecomment-534547652.
This PR does not add fallbacks of the whitepoint argument. Therefore, there are no changes to the public API.
You can squash these commits when merging.
=> Clean conversion methods up

src/algorithms.jl
This is what was originally part of PR #427.
The `find_maximum_chroma` has not been exported yet, so the impact of this change should be minor.
=> Improve type stability in `find_maximum_chroma`

.github/workflows/TagBot.yml
Closes #443
Hopefully I did all the steps correctly...if not, let me know.
=> Add ssh key for TagBot.yml

src/Colors.jl, src/parse.jl
This is an expensive method to infer (>50ms on my machine) and it
has never precompiled successfully. It turns out that
calling it during module definition makes it non-precompilable.
I am guessing that this is because there end up being backedges
to something in the temporary process that does the precompilation
that is no longer available (perhaps gensyms in macro expansion?).
In any case, avoiding the call works around the problem.
=> Successfully precompile `_parse_colorant`

src/utilities.jl, test/utilities.jl
Removes the use of `convert` inside `mapc` which for some reason isn't type-stable. It isn't needed anyway as the previous conversion of `weighted1` has the same effect.
~~This type instability doesn't have a major performance impact, but makes it difficult to test inference in other packages that use this where type instability does have a major impact.~~
See JuliaGraphics/ColorSchemes.jl#52
=> fix type instability in weighted_color_mean

Project.toml
TagBot must be updated before registering v0.12.5 (cf. #449).
=> Version 0.12.5

src/display.jl
This reduces the risk of having invalid suffixes when converting numbers to strings. This also supports indices that start with other than 1.
There is almost no improvement in performance.
=> Make display of color swatches slightly robust

src/utilities.jl
This helps a bit in troubleshooting issue #459.
Probably, ColorTypes v0.11 will be released soon, and its `[compat]` support will be the last patch for Colors v0.12 series.
=> Add compat note for `style` option of `hex()`

Project.toml, docs/src/colormapsandcolorscales.md, test/utilities.jl
`InteractiveUtils` is not used (imported) in `module Colors`, and is a standard library. Therefore, it should be safely removed from the `[deps]` section.
=> Version 0.12.7

docs/src/colormapsandcolorscales.md, src/Colors.jl, src/display.jl, test/display.jl
This is useful to avoid conversion errors in advance.
Since `NaN`/`Inf` may be caused by bugs, implicit clamping is not performed. This is in contrast to clamping for out-of-gamut colors.
Closes #469.
=> Implement `showable` to check that all components are finite

.github/workflows/UnitTest.yml, Project.toml, src/precompile.jl, test/conversion.jl
This adds the support for [ColorTypes v0.11](https://github.com/JuliaGraphics/ColorTypes.jl/pull/231). The changes in ColorTypes v0.11 are mainly related to ColorVectorSpace, and do not directly affect the Colors.jl API.
This also modifies the CI settings and removes `@assert`s from the precompilation script.
=> Version 0.12.8

src/conversions.jl
I found some type instability issues while tackling JuliaLang/julia#35972 or #425. Unfortunately, this doesn't solve JuliaLang/julia#35972, and doesn't provide much performance improvement.
~This is a successor of PR #424.~ (Merged. However, I'm still looking for a way to solve #425.)
This should be the next v0.13 material since this changes the conversion results slightly.
=> Improve type stability in conversion methods

docs/src/colormapsandcolorscales.md, src/utilities.jl, test/utilities.jl
This adds a method of `weighted_color_mean` which takes collections of weights and colors. This is not efficient or accurate implementation, but it is simple.
Closes #467, cc: @cjwyett
=> Add support for `weighted_color_mean` for multiple colors

src/differences.jl, test/colordiff.jl
This makes `DE_94` and `DE_CMC` quasimetric. Within those metrics, the first argument of `colordiff` is taken as the reference color. This adds the weight parameters `k1` and `k2` to `DE_94`.
This also makes the omission of the metric constructor arguments more flexible.
~**Edit:** `DE_94` seems to have a similar problem. I will fix it as well.~ Done
Fixes #438
=> Fix `DE_94` & `DE_CMC` color difference metrics

docs/src/colordifferences.md, docs/src/constructionandconversion.md, src/Colors.jl, src/differences.jl, src/utilities.jl, test/utilities.jl
This exports the re-implemented version of `mean_hue`.
This is a preparation for future performance improvements, and is not in itself a change intended to improve accuracy or speed. This will slightly affect the calculation results.
=> Clean up "src/differences.jl"

src/utilities.jl, test/utilities.jl
`hex(::ColorAlpha)` will now return "RRGGBBAA".
This also removes the deprecated `Base.hex(::Colorant)`.
I had expected that reaching v1.0 would happen somewhat sooner, but it has been a year since the release of v0.12.0.:sweat_smile: So, I think this should be applied in v0.13.0.
=> Change the default alpha position for `hex(::ColorAlpha)`

src/parse.jl
cf. https://github.com/JuliaGraphics/Colors.jl/issues/419
=> Remove deprecated `color(::AbstractString)`

src/conversions.jl, src/utilities.jl, test/utilities.jl
`pow5_12` is used in the `XYZ{Float64}`-->`RGB` conversion.
This ensures sufficient accuracy (~3 ULP) in the range of [0.003, 1], which is typically required for the conversion.
`@inline` could be a workaround for the problem with precompilation.
I am planning a `Float32` version. However, for now (i.e. without PR #482), the result will be promoted to `Float64` within the transform matrix.
**Edit:** see https://github.com/JuliaGraphics/Colors.jl/pull/485#issuecomment-856727816
cf. #483
=> Improve speed of `pow5_12(::Float64)` and accuracy of `pow5_12(::Float32)`

src/utilities.jl, test/utilities.jl
`Colors.delta_h` has been introduced in the PR #476.
```julia
julia> Colors.delta_h(LCHab(50, 60, 135.123f0), LCHab(90, 80, 135.123f0))
0.0f0         # master (Julia v1.6.1)
-1.2973305f-5 # master (Julia v1.0.5)
0.0f0         # this PR
```
=> Reduce rounding errors in `delta_h`

docs/src/colordifferences.md, src/conversions.jl
This adds the separate methods for omitting the white points to facilitate constant folding.
This also suppresses the promotion of intermediate variables to `Float64` due to white point being `XYZ{Float64}`. (cf. issue #477)
A part of this PR has been separated from PR #482.
I'm not sure of the reason, but I avoid `mapc` for now because it makes the precompilation problem worse. This PR does not solve the precompilation problem. :confused:
=> Improve `Lab`<-->`XYZ` conversions

docs/make.jl
In Documenter.jl v0.27, SVG images ("image/svg+xml") are now embedded using the `<img>` tag.
For example:
Documenter v0.27: https://juliagraphics.github.io/Colors.jl/dev/constructionandconversion/#Available-colorspaces
Documenter v0.26: https://juliagraphics.github.io/Colors.jl/v0.12/constructionandconversion/#Available-colorspaces
This avoids the limitations of the `<img>` tag.
Note that the swatch display which is implemented in Colors.jl uses the `<img>` tag.
=> Change SVG images in the document to be output as "text/html"

src/algorithms.jl, src/conversions.jl
This reduces the hard-coded constants.
This also avoids unnecessary gamma correction in the out-of-gamut checking.
A part of this has been separated from PR #482.
=> Make `MSC` & `find_maximum_chroma` robust to implementations of conversions

docs/src/colordifferences.md, src/conversions.jl, src/utilities.jl, test/utilities.jl
This makes the cube root to be inlined to make it suitable for vectorization.
This is intended to reduce precompilation problems rather than increase the speed. (cf. #425)
~This also optimizes the `pow5_12(::Float32)`.~ **Edit**: I will separate this into a new PR.
=> Make the cube root to be inlined

docs/src/colordifferences.md, src/algorithms.jl, src/conversions.jl, src/utilities.jl, test/conversion.jl, test/utilities.jl
This also changes the definition of the sRGB transform matrix slightly. (cf. https://github.com/JuliaGraphics/Colors.jl/issues/355#issuecomment-539524932)
cf. #477
=> Use `Float32` for the matrix coefficients for low precision colors

src/conversions.jl, src/utilities.jl
Without PR #482, `pow5_12(::Float32)` was never called because linear RGB values are promoted to `Float64` in the transform matrix multiplication.
The new `pow5_12(::Float32)` has an accuracy of about 0.5 ULP.
=> Optimize `pow5_12(::Float32)`

docs/src/colordifferences.md, src/utilities.jl, test/utilities.jl
The conventional version using `atand` has a larger numerical error because `rad2deg` is applied to the `atan` result.
This improves the accuracy and speed by making the internal representation conform to degrees and by simplifying the handling of exceptional cases.
This change should be made in ColorTypes.jl, but for the convenience of development, it is implemented once in Colors.jl.
```julia
julia> hue(Lab(50, big(50.85106f0), big(-24.293373f0))) |> Float32
334.4645f0
julia> hue(Lab(50, 50.85106f0, -24.293373f0))
334.4645f0
julia> hue(ALab(50, 50.85106f0, -24.293373f0)) # all versions except `Lab` and `Luv` are old at the moment
334.46454f0
```
=> Optimize `ColorTypes.hue(c)`

src/utilities.jl, test/utilities.jl
This avoids the loss of significance when the difference in hue is small. (cf. https://github.com/JuliaGraphics/Colors.jl/issues/477#issuecomment-869102943)
This results in a slowdown of `delta_h`, but it is negligible compared to the total cost of `DE_2000`.
This is one of the preparations for PR #494.
```julia
julia> a = Lab(40, 4, 80); b = Lab(50, 5, 101);
julia> Colors.delta_h(a, b)
-0.043853227f0 # master
-0.04444444f0  # this PR
julia> Colors.delta_h(Lab{BigFloat}(a), Lab{BigFloat}(b))
-0.04444444308963756431578907136117476345617361364807484182394389220997687609203497
```
=> Improve accuracy of `delta_h` for small differences

docs/src/colordifferences.md, src/utilities.jl, test/utilities.jl
This is a follow-up to PR #501.
This avoids the loss of significance when |Δh| > 90 deg.
This also adds `delta_c` to improve accuracy of `Lab{Float32}` chroma differences.
```julia
julia> a, b = Lab(60, -36.75124f0, -4.8861504f0), Lab(80, 4.557669f0, -2.6522517f0);
julia> Colors.delta_h(a, b)
-26.459148f0 # master
-26.459143f0 # this PR
julia> Colors.delta_h(Lab{BigFloat}(a), Lab{BigFloat}(b))
-26.45914388977270124791437895470628506022253442451544986697371328558951044881593
julia> chroma(a) - chroma(b)
31.801413f0
julia> Colors.delta_c(a, b)
31.801414f0
julia> chroma(Lab{BigFloat}(a)) - chroma(Lab{BigFloat}(b))
31.80141452063303790359376637963574569550424247180931525255208635027325242378461
```
=> Improve accuracy of `delta_h` for large hue differences

docs/src/colordifferences.md, src/differences.jl, src/utilities.jl, test/colordiff.jl
This speeds up the calculation of `DE_2000` while ensuring the accuracy of `5e-5`.
This changes not only the type of intermediate variables, but also the return type. (cf. #477)
~This also fixes typos in the `DE_2000` test data.~ (separated to #499)
```julia
julia> a, b = Lab(50, -1.3802, -84.2814), Lab(50, 0.0000, -82.7485);
julia> colordiff(Lab{BigFloat}(a), Lab{BigFloat}(b)) |> Float64
0.9999988647524654
julia> colordiff(Lab{Float64}(a), Lab{Float64}(b))
0.9999988647524661
julia> colordiff(Lab{Float32}(a), Lab{Float32}(b))
1.0000001f0
julia> colordiff(Lab{BigFloat}.(Lab{Float32}.((a, b)))...) |> Float32
0.99999994f0
```
```julia
julia> a = Lab{Float32}.(rand(RGB{Float32}, 1000, 1000));
julia> b = Lab{Float32}.(rand(RGB{Float32}, 1000, 1000));
julia> @btime colordiff.($a, $b);
174.563 …
```
=> Use `Float32` to calculate `DE_2000` for low precision colors

src/differences.jl
This is a follow-up to PR #494.
For consistency with `DE_2000`, this allows `Float32` to be used for other metrics.
=> Use `Float32` to calculate `colordiff` for low precision colors

src/colormaps.jl, src/conversions.jl, test/colormaps.jl
This changes the type used for internal operations from `Lab{Float64}` to `Lab{Float32}`.
This also removes the unnecessary sRGB gamma operations and `deleteat!`.
Note that `@nospecialize` is almost useless because of the keyword arguments.
```julia
julia> @btime distinguishable_colors(10);
10.832 ms (896527 allocations: 14.88 MiB) # master w/o recompilation
5.104 ms (50998 allocations: 1.50 MiB)    # master w/ recompilation
2.675 ms (9070 allocations: 213.08 KiB)   # this PR
```
Closes #477
=> Optimize `distinguishable_colors`

src/differences.jl, src/utilities.jl, test/utilities.jl
This calculates the bisection vector in Cartesian space and then obtains its angle.
~This is still in the idea stage and has not been fully studied for accuracy and speed; I would like to prioritize the merging of PR #494.~
|1000000 samples  | mean error | maximum error |
|:----------------|-----------:|--------------:|
|`Float32` before | 6.4e-6 °   | 4.0e-5 °      |
|`Float32` after  | 4.2e-6 °   | 2.3e-5 °      |
|`Float64` before | 12.0e-15 ° | 7.7e-14 °     |
|`Float64` after  | 7.7e-15 °  | 4.4e-14 °     |
Unfortunately, there is little speed improvement.
```julia
julia> a = Lab{Float32}.(rand(RGB{Float32}, 1000, 1000));
julia> b = Lab{Float32}.(rand(RGB{Float32}, 1000, 1000));
julia> @btime colordiff.($a, $b);
69.342 ms (2 allocations: 3.81 MiB) # before
67.334 ms (2 allocations: …
```
=> Improve accuracy of `mean_hue` for `Lab` and `Luv` colors

src/algorithms.jl, src/conversions.jl, src/utilities.jl, test/utilities.jl
This adds `sincos360`, the rough equivalent of `sincosd`.
The `sincos360` is less accurate than `sincosd`, but in many cases more accurate than `sincos(deg2rad(x))`.
Also, while `sincosd(Inf)` throws a `DomainError`, `sincos360(Inf)` returns `(NaN, NaN)`.
This is mainly intended to mitigate precompilation and inlining issues. (cf. issue #496)
This might have to be moved to ColorTypes.jl as well as `atan360`. (cf. PR #495) Fortunately, moving those methods to ColorTypes.jl seems to maintain the benefits. However, I'm not sure why the problem occurs with `Base`.
=> Implement `polar_to_cartesian`

src/conversions.jl, src/precompile.jl, src/utilities.jl
This uses the `cnvt` instead of the top-level `convert` when source and destination are both known colors.
This also blocks the propagation of inference failures by adding type assertions to the result of `convert`.
~However, these changes do not solve the essential problem (#496). So, this PR is for reference only, and I have no plans to merge this for now.~
By PR #510, we can see the practical effects, e.g.：
```julia
julia> lchab = rand(LCHab, 1000, 1000);
julia> convert.(RGB{Float64}, lchab); # compilation
julia> @time convert.(RGB{Float64}, lchab);
0.174340 seconds (4.00 M allocations: 144.959 MiB, 37.16% gc time) # before
0.137165 seconds (2.00 M allocations: 83.923 MiB, 40.44% gc time)  # after
```
I haven't solved the problem yet, though.
=> Mitigate inference problems in color conversions

Project.toml, src/utilities.jl, test/runtests.jl
The fix is to adhere more closely to the minimalistic
[AbstractArray interface](https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-array).
Fixes #512
=> Fix an ambiguity with AbstractTrees

docs/colormapparams.jl, docs/crosssectionalcharts.jl, docs/make.jl, docs/png16x16.jl, docs/src/colormapsandcolorscales.md, docs/src/references.md
This adds visual examples for `sequential_palette`.
Closes #265
=> Update documentation for colormaps

src/algorithms.jl
This fixes the specific demo in #496. These constants were added in 8f6550dd, but there is nothing wrong with that PR---those should be perfectly reasonable operations to perform during package definition.
The origin of the problem is a julia bug whose identity remains mysterious. Some diagnostics were done in https://github.com/JuliaLang/julia/issues/35972, but this particular case appears to be distinct from the mechanism identified there and has not yet been isolated.  This is a simple workaround.
=> Work around #496 for Luv, Lab

src/colormaps.jl, test/conversion.jl
This may not be everything, but a few simple cases that were easy to update
=> Update a few cases where array indices are assumed

docs/src/constructionandconversion.md
`transparent` and `opaque` should be appear in doc search results.
=> add note on transparent - opaque conversions

src/algorithms.jl, test/algorithms.jl
Summary: Fixed a typo causing incorrect simulation of tritanopic color vision deficiencies. Also added tests for this corrected behavior.
This is my first pull request, I apologize if I have done anything incorrectly. I have been working with simulating various color vision deficiencies, and I noticed that the simulation for tritanopia was not producing results that I expected. Looking into the code in the function `tritanopic` had a typo:
https://github.com/JuliaGraphics/Colors.jl/blob/b550b7bc2f6f27fdf61c30b3215b28df826ceebf/src/algorithms.jl#L138
It should be:
```julia
(one(p) - p) * q.s + p * (-(a*q.l + b*q.m)/c))
```
This error can be easily observed when inspecting the behavior of the function at p=0 (no photopigment loss):
This can also be seen in the RGB values:
```julia
rgb = …
```
=> Fixed tritanopia simulation

src/differences.jl
This makes it less likely that `muladd` will make the difference between being fused or not.
=> Improve stability of accuracy in `DE_BFD`

docs/make.jl, docs/src/constructionandconversion.md
=> Fix name collision in document examples

Project.toml
I tested `ColorVectorSpace`, `ImageCore`, `Images`, `Cairo`, and `Makie` as downstream packages (on CI).
=> Version 0.12.11

Project.toml, src/Colors.jl, src/conversions.jl
This removes the deprecated bindings for RGB4 and RGB1, see discussion:
https://github.com/JuliaIO/ImageMagick.jl/issues/235
and similar fix in ColorTypes.jl
https://github.com/JuliaGraphics/ColorTypes.jl/pull/312
It also requires the new version of ColorTypes in Compat, but that will cause failures until that version is registered. 
CC: @ViralBShah, @ararslan
=> Remove deprecated bindings RGB4 RGB1

src/utilities.jl
The functions need to be able to deal with infinities but fastmath assumes that arguments and results are not so.
On 1.12:
```
julia> Colors.atan360(-Inf, Inf)
NaN
```
with fastmath removed:
```
julia> Colors.atan360(-Inf, Inf)
315.0
```
I haven't looked into any of the other fastmath usages in this package.
=> remove invalid fastmath usage in atan360

src/utilities.jl
The test at https://github.com/JuliaGraphics/Colors.jl/blob/f143ad9e9e457d0b1c8f94cca60bbc67746402f7/test/utilities.jl#L223 runs a function that stack overflows. Continuing the process after a stack overflow is not recommended and julia 1.12 prints:
```
Warning: detected a stack overflow; program state may be corrupted, so further execution might be unreliable.
```
Instead, catch if we have no match after the promote and throw a normal error.
=> avoid stackoverflow when passing two types that can not be promoted to a matching types in `mean_hue`
