README.md
This may help people who didn't notice the post to julia-users
=> Add migration tips

images/color_names_sorted.svg, images/draw_swatches.jl
although the output SVG is a bit different (colors are in a slightly
different order from before), this particular file is only a
quick-reference/pretty handout, so the changes aren’t significant… :)
=> fixed for 0.4/Colors.jl

src/conversions.jl, test/conversion.jl
=> Define fallback for stripping the alpha channel. Fixes Images #382.

REQUIRE, src/Colors.jl, src/conversions.jl, src/parse.jl, test/conversion.jl
Should fix https://github.com/timholy/Images.jl/pull/445#issuecomment-189866806. CC @Evizero.
=> Convert to Gray using round, not trunc

REQUIRE, src/Colors.jl, src/conversions.jl, src/display.jl, test/conversion.jl
While profiling something I noticed these conversions weren't quite as careful as they should be.
=> More careful conversions to RGB24/ARGB32

README.md
=> add example of creating colorant using hex codes

src/colormatch.jl
This will fix the bug
```
julia> Colors.colormatch(359.1)
ERROR: DimensionMismatch("dimensions must match")
...
```
=> Fix vector construction

.travis.yml, REQUIRE, src/differences.jl
=> fix depwarns under 0.7 and bump REQUIRE and CI to 0.6

REQUIRE, test/conversion.jl
This fixes some deprecation warnings
=> Use isapprox in tests

.travis.yml, Manifest.toml, Project.toml, REQUIRE, appveyor.yml, src/Colors.jl, src/conversions.jl, src/utilities.jl
This improves on Jeff's PR, and passes tests locally.  Let's see what CI says.
=> Better v1.0 updates

src/colormaps.jl, test/colormaps.jl, test/runtests.jl
Detected by IndirectArrays tests
=> Fix depwarn in colormap and add tests for colormap

Project.toml
=> Update version in Project.toml.

docs/src/colorspaces.md
Seems outdated now that #308 has been merged.
=> Remove parenthetical note about rebeccapurple

src/display.jl, test/colormaps.jl
Fixes #328. Two questions:
1) I couldn't find the show method in tests - should I add one? If so, where makes the most sense?
2) Were you suggesting that I *add* the `transpose()` method for colors, or is this sufficient?
=> Use ReshapedArray for show()

README.md
Farewell Pkg.evaluator badges, you were nice.
=> Update README, remove Pkgeval badges

src/colormaps.jl, src/conversions.jl, test/algorithms.jl, test/conversion.jl, test/din99.jl
This does some long needed-maintenance. Most importantly, I finally just took the DIN99 changes despite the lack of good tests. (Would be really good to have those...)
=> Several fixes

src/conversions.jl, test/conversion.jl
This also provides methods for Gray24 conversion.  Fixes #377.
=> Use RGB accessor functions Gray conversion

Project.toml
This is a patch release for the issue #386 (fixed by #390).
=> Version 0.11.1

Project.toml, src/Colors.jl
Ref https://github.com/JuliaLang/julia/issues/34121
=> Work around segfault on Julia 1.0.x

src/Colors.jl, src/colormatch.jl, test/colormatch.jl, test/runtests.jl
=> Export `CIE2006_2_CMF` and `CIE2006_10_CMF` (Fixes #375)

Project.toml, src/utilities.jl, test/utilities.jl
=> Fix problem with `hex(::Gray{Bool})`

Project.toml, test/conversion.jl
This also removes a test, which ColorType should be responsible for.
=> Version 0.12.3

src/differences.jl, test/colordiff.jl
This adds the support for `TransparentColor` inputs of `colordiff`. If the alpha of the `TransparentColor` input is not 1, an error is thrown. (There is room for improvement in the content of the message.)
```julia
julia> colordiff(RGBA(0.35, 0.18, 0.90, 1), RGBA(0.34, 0.18, 0.90, 1))
0.2965835193560762
julia> colordiff(RGBA(0.35, 0.18, 0.90, 0.5), RGBA(0.34, 0.18, 0.90, 0.5))
ERROR: ArgumentError: cannot evaluate the difference in transparent colors.
Their appearance depends on the backdrop.
```
This also adds basic tests for `colordiff` and fixes the conversion error within `DE_BFD`.
Fixes #437
=> Add error message for `colordiff` with transparent color inputs

src/algorithms.jl, test/algorithms.jl
Fixes #435
I think this could be v0.12 material.
=> Generalize XYZ and LMS arithmetic

README.md
https://github.com/JuliaGraphics/Colors.jl/issues/447
CC @tbenst
=> Add link to ColorTypes in README

docs/src/namedcolors.md, src/names_data.jl, src/parse.jl
=> Add cross-references for named colors

src/conversions.jl, test/conversion.jl
This avoids stack overflow in conversions for color types which are not defined in ColorTypes.jl.
This also attempts to convert via `RGB` instead of directly to the destination type as a fallback. That improves support for source types other than `Color3`. In other words, if you define a new color type, you should be able to achieve conversions with other color types, at least by implementing conversions with `(Abstract)RGB`.
Technically speaking, this is a breaking change, but I don't think it will have any negative impact unless the conversion methods are overloaded improperly.
Fixes #465
=> Fix stack overflow in undefined color space conversions

README.md
=> doc badge links to https

src/conversions.jl
This is an `Luv` variation of the PR #486.
Closes #425
=> Improve `Luv`<-->`XYZ` conversions

test/conversion.jl
PR #533 may solve the specific problem, but the similar problem could happen in the future.
This allows the problems to be properly postponed, and the test would no longer be stale with breakage.
The real problem, however, is the insufficiency of maintainers.
I am never the solution to the maintenance problem and I do not have the solution.
=> Add filter for unsupported colors in conversion test

.github/workflows/CompatHelper.yml, .github/workflows/Documentations.yml, .github/workflows/Invalidations.yml, .github/workflows/TagBot.yml, .github/workflows/UnitTest.yml
These changes are mostly unnecessary, but it is worth backporting just for `workflow_dispatch`.
=> Update workflows (Backport #540 and #541)

test/algorithms.jl
cf. https://github.com/JuliaGraphics/Colors.jl/pull/525#discussion_r1597427999
=> Fix test for CVD
